name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run Cypress tests
      run: npx cypress run --config supportFile=false

    - name: Run Postman/Newman tests
      run: |
        npm install -g newman
        newman run Rick&Morty.postman_collection.json

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          cypress/screenshots
          cypress/videos
          newman/
